### ISSUE TITLE
SyntaxError when trying to run it on Node 0.12

### ISSUE THREAD

**Issue by alebelcor** [egoist/testen#8]
According to the `package.json` this runs in `>=0.10.0` but I'm on `0.12.13` and this is showing up:

```
/usr/local/lib/node_modules/testen/testen:7
const fs = require('fs')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Apparently you can' t use `const` in strict mode.

Are there plans to make this compatible?

Thanks!

**Comment by alebelcor** [comment]
I just saw in the `README.md`:

> You should have `nvm` and `node >= 4` installed.

Should the `package.json` be updated then?

**Comment by egoist** [comment]
Updated, thx for reminding 😀 🎉
